### ISSUE TITLE
Understanding your implementation.:  Help

### ISSUE THREAD

**Issue by agugan** [jimmaaay/j-carousel#1]
Hi Jimmy, I have a doubt in your implementation.
`const lastTick = start === false ? false : ((timestamp - start) + HALF_A_FRAME) >= duration;`

How does this line works?
I am converting your implementation to TS and i am getting a compiler error stating 
`The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.`.
I have a little trouble in understanding this.

**Comment by jimmaaay** [comment]
My guess is that you've given the wrong type to one of the variables.

What type have you set on `start`?

**Comment by agugan** [comment]
No explicit type is set on start, but it is being inferred as boolean as of now. but HALF_A_FRAME is being is set as number.

[Update :] Thanks Jimmy, I tried setting start as any and continued the execution and now it works.
